version: '3.9' 

services: 
  frontend:
    build: 
      context: ./gestione-finanze-frontend
      dockerfile: Dockerfile
    ports:
      - "80:80"
    networks:
      - mynetwork

  backend:
    build:
      context: ./gestione-finanze-backend
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - DATABASE_URL=jdbc:mysql://my-sql:3306/finanze
      - DATABASE_USERNAME=root
      - DATABASE_PASSWORD=Test123-
    depends_on:
      my-sql:
        condition: service_healthy
    networks:
      - mynetwork

  my-sql:
    container_name: my-sql
    image: mysql:5.7
    ports:
      - "3306:3306"
    volumes:
      - ./MySQL:/docker-entrypoint-initdb.d
    environment:
      MYSQL_DATABASE: finanze
      MYSQL_ROOT_PASSWORD: Test123-
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 10
    networks:
      - mynetwork

networks:
  mynetwork:
    driver: bridge
